### PR TITLE
:globe_with_meridians:Fix network communications

### LINKED ISSUE #102: Remove code duplication between `Input` and `Attack` systems
While refactoring all our systems to use the new `Zipper` class, I noticed that there is code duplication between the `Input` and `Attack` systems. As of now, `Attack` handles the creation of projectiles shot by enemies, whereas `Input` handles (besides other things) the creation of projectiles shot by the player, in exactly the same way the `Attack` system does.

A refactor could make the `Input` system manage a `Gun` component attached to the player, which could then be read by the `Attack` system to create player projectiles

### PR DESCRIPTION
**Pull request by ClementBaziret**
This pull requests fixes a lot of problems that were present in the network communications between the server and the client.

- The server and the client now shares a list of network ID that corresponds to each entities in the server and the client. This helps managing the entities and remove the need to synchronize the client game engine with the server

Close #102

### CODE REVIEW

File: plugins/components/acceleration/Acceleration.hpp [hunk 1]
```diff
@@ -171,8 +166,15 @@ namespace Components {
...
+            std::unique_ptr<Components::Acceleration> acceleration = engine.newComponent<Components::Acceleration>(static_cast<int32_t>(forwardVal), static_cast<int32_t>(backwardVal), static_cast<int32_t>(rightVal), static_cast<int32_t>(leftVal));
+            Components::IComponent *rawComponent = acceleration.get();
+            engine
+                .getRegistry()
+                .componentManager()
+                .addComponent<Components::Acceleration>(to, std::move(acceleration));
+            std::cerr << "Acceleration component added to entity: " << to << std::endl;
+            engine.updateComponent(to, rawComponent->getId(), rawComponent->serialize());
+            std::cerr << "Acceleration component updated" << std::endl;
             std::cout << std::endl;
```
Comment (ClementBaziret) [inline plugins/components/acceleration/Acceleration.hpp:178]: Some debug left on purpose ?

Comment (ClementBaziret) [inline plugins/components/acceleration/Acceleration.hpp:178]: Is it necessary to get the raw pointer ? Couldn't you just do `engine.updateComponent(to, acceleration->getId(), acceleration->serialize());`

Also is the debug left on purpose ?

Comment (ClementBaziret) [reply plugins/components/acceleration/Acceleration.hpp:178]: This comment applies to all the components modified : Acceleration, Collider, Controllable, Damage, DeathRange, Gun, Health, Position, Scale, SpriteID, Type, Velocity and Visible

File: plugins/systems/move/Move.cpp [hunk 2]
```diff
@@ -43,7 +43,7 @@ void Systems::MoveSystem::run(Engine::GameEngine &engine)
                 vel->floatY *= factor;
                 vel->x = (int)vel->floatX;
                 vel->y = (int)vel->floatY;
-                engine.updateComponent(i, vel->getId(), vel->serialize());
+                // engine.updateComponent(i, vel->getId(), vel->serialize());
```
Comment (ClementBaziret) [inline plugins/systems/move/Move.cpp:46]: Is this comment intentionnal ?

File: plugins/systems/sfml/Sfml.cpp [hunk 3]
```diff
@@ -47,15 +47,14 @@ void Systems::Sfml::init(Engine::GameEngine &engine)
...
-
-    }
+    // if (!__music.openFromFile("./assets/background.mp3")) {
+    //     std::cerr << "Failed to load music" << std::endl;
+    //     return;
+    // } else {
+    //     std::cerr << "Music loaded" << std::endl;
+    //     __music.play();
+    //     __music.setLoop(true);
+    // }
```
Comment (ClementBaziret) [inline plugins/systems/sfml/Sfml.cpp:57]: We can uncomment this

File: src/ECS/entity/EntityManager.hpp [hunk 4]
```diff
@@ -35,6 +35,21 @@ namespace ECS {
...
+                //     std::cerr << "Error: Entity with id n°" << e << " already exists" << std::endl;
+                //     return;
+                // }
+                while (entity >= __entities.size()) {
+                    __entities.push_back(Entity(__nextEntityId++));
+                }
+                __entities.insert(__entities.begin() + entity, Entity(entity));
+                return __entities.at(entity);
+            }
+
```
Comment (ClementBaziret) [inline src/ECS/entity/EntityManager.hpp:52]: @Tugduoff do you use this function ? If not we can delete it.

File: src/ECS/registry/Registry.hpp [hunk 5]
```diff
@@ -75,6 +76,7 @@ namespace ECS {
                 this->__componentManager.removeAllFromEntity(entity);
                 this->__entityManager.killEntity(entity);
                 for (auto const &cb : this->__killCallbacks) {
+                    std::cerr << "Calling kill callback for entity n°" << entity << std::endl;
```
Comment (ClementBaziret) [inline src/ECS/registry/Registry.hpp:79]: Debug left on purpose ?

File: src/network/RTypeClient.cpp
Comment (ClementBaziret) [inline src/network/RTypeClient.cpp:1]: Do we leave all the debug in this file ?

File: src/network/UDPServer.cpp [hunk 6]
```diff
@@ -192,39 +196,56 @@ void UDPServer::remove_client(const udp::endpoint& client) {
 
 void UDPServer::create_entity(const ECS::Entity &entity) {
     uint8_t opcode = 0x0;
-    uint16_t entity_id = static_cast<uint16_t>(entity);
-    entity_id = htons(entity_id);
+    uint32_t networkId = _nextNetworkId;
+    _nextNetworkId++;
+    _entitiesNetworkId.insert({entity, networkId});
+    // uint16_t entity_id = static_cast<uint16_t>(entity);
```
Comment (ClementBaziret) [inline src/network/UDPServer.cpp:202]: We can remove this commented line

File: src/network/UDPServer.cpp [hunk 7]
```diff
@@ -192,39 +196,56 @@ void UDPServer::remove_client(const udp::endpoint& client) {
...
-    entity_id = htons(entity_id);
+    uint32_t networkId = _entitiesNetworkId.at(entity);
+
+    std::cerr << "Deleted entity n°" << entity << " in local" << std::endl;
+    std::cerr << "Entity network id: " << networkId << std::endl;
+
+    _entitiesNetworkId.erase(entity);
+    networkId = htonl(networkId);
+
+    std::cerr << "Entity " << entity << " deleted. Now sending infos to the client" << std::endl;
```
Comment (ClementBaziret) [inline src/network/UDPServer.cpp:231]: Debug left on purpose ?

File: src/server/Main.cpp [hunk 8]
```diff
@@ -97,15 +97,12 @@ int main() {
...
     };
 
     try {
-        engine.registerComponent<Components::Visible>("./plugins/bin/components/", "Visible");
-        engine.registerComponent<Components::Health>("./plugins/bin/components/", "Health");
-        engine.registerComponent<Components::Collider>("./plugins/bin/components/", "Collider");
-
-        engine.loadSystems("./src/server/configServer.cfg");
+        
+        std::cerr << ntohl(1291845632) << std::endl;
```
Comment (ClementBaziret) [inline src/server/Main.cpp:105]: debug left on purpose ?

File: src/server/Main.cpp [hunk 9]
```diff
@@ -129,9 +126,25 @@ int main() {
...
+        // engine.getRegistry().componentManager().
         while(server.client_endpoints.empty())
             server.start_receive();
 
+        std::thread io_thread([&io_context]() { io_context.run(); });
+        std::thread io_thread1([&io_context]() { io_context.run(); });
+        std::thread io_thread2([&io_context]() { io_context.run(); });
+        std::thread io_thread3([&io_context]() { io_context.run(); });
+        std::thread io_thread4([&io_context]() { io_context.run(); });
+
```
Comment (ClementBaziret) [inline src/server/Main.cpp:147]: I am not sure if this really help since all the operations that `io_context.run()` are already asynchronous.

**Review by ClementBaziret — COMMENTED** [review]
There is just leftovers from all the tests we did but overall this seems pretty good :saluting_face:

File: src/network/UDPServer.cpp (hunk 6 above)
Comment (ClementBaziret) [reply src/network/UDPServer.cpp]: Fixed

File: plugins/systems/sfml/Sfml.cpp (hunk 3 above)
Comment (ClementBaziret) [reply plugins/systems/sfml/Sfml.cpp]: Uncommented it

File: plugins/systems/move/Move.cpp (hunk 2 above)
Comment (Tugduoff) [reply plugins/systems/move/Move.cpp:46]: Yes it is, we dont need to send data about the velocity component to the client. He doesn't care about it ^^ !

The only components he cares about are : 
- Action
- SpriteId
- Position

File: src/ECS/entity/EntityManager.hpp (hunk 4 above)
Comment (Tugduoff) [reply src/ECS/entity/EntityManager.hpp:52]: I don't, we can safely delete it
image

File: src/ECS/registry/Registry.hpp (hunk 5 above)
Comment (Tugduoff) [reply src/ECS/registry/Registry.hpp:79]: For now, its better to leave it! Later on we might want to remove all debugs to improve efficiency !

File: src/network/RTypeClient.cpp
Comment (Tugduoff) [reply src/network/RTypeClient.cpp:1]: Later on i believe we will have to! For now i dont think it's necessary. Maybe we can do a branch in order to remove all of them (just comment) for the follow up, we will uncomment them afterwards

File: src/network/UDPServer.cpp (hunk 7 above)
Comment (Tugduoff) [reply src/network/UDPServer.cpp:230]: Yes indeed

File: src/server/Main.cpp (hunk 8 above)
Comment (Tugduoff) [reply src/server/Main.cpp:105]: Nope, totally forgot about this one! Sorry

File: src/server/Main.cpp (hunk 9 above)
Comment (Tugduoff) [reply src/server/Main.cpp:147]: It says in the documentation of the run() function : 
``The run() function blocks until all work has finished and there are no more handlers to be dispatched, or until the io_context has been stopped.

Multiple threads may call the run() function to set up a pool of threads from which the io_context may execute handlers. All threads that are waiting in the pool are equivalent and the io_context may choose any one of them to invoke a handler.``

So i think its helping, tho, as of right now i dont think this implementation is usefull since the lags are actually in the client side.

A good thing to note is that we could create one thread per client using this format.

File: plugins/components/acceleration/Acceleration.hpp (hunk 1 above)
Comment (Tugduoff) [reply plugins/components/acceleration/Acceleration.hpp:178]: Since we are moving newly created components instead the componentManager, we loose the unique ptr. So we get the raw ptr before hand in order to still be able to call the getId() and serialize() functions.

Comment (ClementBaziret) [reply plugins/components/acceleration/Acceleration.hpp:178]: Oh okay I see, very well.

File: plugins/systems/move/Move.cpp (hunk 2 above)
Comment (ClementBaziret) [reply plugins/systems/move/Move.cpp:46]: Okay :saluting_face:

File: src/ECS/entity/EntityManager.hpp (hunk 4 above)
Comment (ClementBaziret) [reply src/ECS/entity/EntityManager.hpp]: I removed it then :saluting_face:

File: src/network/UDPServer.cpp (hunk 7 above)
Comment (ClementBaziret) [reply src/network/UDPServer.cpp:230]: okay

File: src/server/Main.cpp (hunk 8 above)
Comment (ClementBaziret) [reply src/server/Main.cpp]: No problem, as long as it is removed in the end :saluting_face:

File: src/server/Main.cpp (hunk 9 above)
Comment (ClementBaziret) [reply src/server/Main.cpp:144]: Oh okay I see, very well

File: src/ECS/registry/Registry.hpp (hunk 5 above)
Comment (ClementBaziret) [reply src/ECS/registry/Registry.hpp:79]: okay

**Review by Tugduoff — APPROVED** [review]
:+1:

**Review by ClementBaziret — COMMENTED** [review]
Seems all good :saluting_face:

File: plugins/components/scale/Scale.hpp [hunk 10]
```diff
@@ -61,6 +61,8 @@ namespace Components {
             __network.width = htonl(width);
             __network.height = htonl(height);
             return std::vector<uint8_t>(__data, __data + sizeof(__data));
+
+            std::cerr << "Serialized Scale component: width=" << width << " height=" << height << std::endl;
```
Comment (C0Florent) [inline plugins/components/scale/Scale.hpp:65]: Do we need to leave this debug?

File: plugins/components/scale/Scale.hpp [hunk 11]
```diff
@@ -77,6 +79,8 @@ namespace Components {
 
             width = ntohl(*reinterpret_cast<uint32_t *>(data.data()));
             height = ntohl(*reinterpret_cast<uint32_t *>(data.data() + 4));
+
+            std::cerr << "Deserialized Scale component: width=" << width << " height=" << height << std::endl;
```
Comment (C0Florent) [inline plugins/components/scale/Scale.hpp:83]: This too?

File: plugins/components/acceleration/Acceleration.hpp (hunk 1 above)
Comment (C0Florent) [reply plugins/components/acceleration/Acceleration.hpp:178]: A good fix would be to create a temporary helper function to handle this temporary problem

**Review by Tugduoff — APPROVED** [review]

File: plugins/components/acceleration/Acceleration.hpp (hunk 1 above)
Comment (Tugduoff) [reply plugins/components/acceleration/Acceleration.hpp]: It has been done !

**Review by ClementBaziret — COMMENTED** [review]
Seems good :saluting_face:

**Review by C0Florent — APPROVED** [review]
Seems all good! :+1:
